### ISSUE TITLE
Rozložení na tabletu zlobí

### ISSUE THREAD

**Issue by JitkaHo** [JitkaHo/PROJEKT-Kontakty#1]
Ahoj Tome,
zkusila jsem si nakódovat ty kontakty.
Myslím, že mobil a PC fungují dobře, ale na tabletu nemůžu přijít na to, jak to zobrazit, aby byly 2 kartičky vedle sebe :(
Poradíš prosím?
děkuju
Jitka

**Comment by tommander** [comment]
<p>Ahoj Jitko, stačí si pohrát trochu s <code>(max-)width</code> u <code>img</code> a spraví se to :)</p>

**Comment by JitkaHo** [comment]
Ahoj Tome,
děkuju, upravila jsem max-width na 100% a vypadá to asi dobře :)
Jitka
